services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: spark_user
      POSTGRES_PASSWORD: spark_password
      POSTGRES_DB: lab_db
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - "./исходные данные:/data"
    networks:
      - spark_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spark_user -d lab_db"]
      interval: 2s
      timeout: 5s
      retries: 10

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-db
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: reports_db
      CLICKHOUSE_USER: spark_user
      CLICKHOUSE_PASSWORD: spark_password
    networks:
      - spark_network
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 2s
      timeout: 5s
      retries: 10

  spark-etl-job:
    image: apache/spark:3.5.1
    container_name: spark-etl-job
    user: "0"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    volumes:
      - .:/opt/spark-data
    networks:
      - spark_network
    command:
      - bash
      - -c
      - |
        /opt/spark/bin/spark-submit --packages org.postgresql:postgresql:42.7.2,ru.yandex.clickhouse:clickhouse-jdbc:0.3.2 /opt/spark-data/spark_etl_star.py
        /opt/spark/bin/spark-submit --packages org.postgresql:postgresql:42.7.2,ru.yandex.clickhouse:clickhouse-jdbc:0.3.2 /opt/spark-data/spark_clickhouse_reports.py
        echo '=== ALL DONE! LAB COMPLETED SUCCESSFULLY! ==='

networks:
  spark_network:
    driver: bridge